### ISSUE TITLE
non-valued html tags are not parsed correctly

### ISSUE THREAD

**Issue by ZingerDerGOD** [HenrikJoreteg/html-parse-stringify#20] opened 2018-06-25 08:38 UTC
Issue itself is well illustrated here: #14 
#19 - fix.

Why separate issue?

1. Attention from the solution owner.
2. Issue is more generic, so fix with this label would semantically fit best, and referring it from subsetting issues would look better.

**Comment by ZingerDerGOD** [comment] 2018-06-25 08:44
In general the idea of simple ad-hoc pure jS based is awesome.
But, i dare to say that without some love this project meant to perish.
@HenrikJoreteg Would be nice to merge this PR, and get it up and running for at least these simple things.

**Comment by HenrikJoreteg** [comment] 2018-06-26 03:32
Hey @ZingerDerGOD, the problem is that I don't use this for anything right now and simply don't have the time to maintain it. I barely have time for the projects i'm already working on. I've added you as a maintainer and if you'll give me your npm name, i can give you publish rights too. Feel free to merge the PR. I just ask that you stay true to the goals of the project, and keep things fast and light.

**Comment by frontmesh** [comment] 2018-07-19 13:48
@HenrikJoreteg there is a PR submitted ? 
I would like to check and merge it, If you don't have time, since I am using this lib as well.

**Comment by frontmesh** [comment] 2018-07-27 11:57
@HenrikJoreteg Thank you! Could I also get npm publish rights ? My npm user is same as github.

**Comment by HenrikJoreteg** [comment] 2018-07-30 04:41
@frontmesh done! Please be cautious and keep tests passing :)

**Comment by pconerly** [comment] 2019-08-04 21:15
I have an issue related to this https://github.com/HenrikJoreteg/html-parse-stringify/issues/27

**Comment by pconerly** [comment] 2019-08-20 22:18
fixed via #28

**Closed by pconerly** 2019-08-20 22:18 UTC
